widgetTheme=widget-themes/oval
primaryColor=#36a9e1
secondaryColor=#86C953
labelColor=#ffffff
hideWhenOffline=false
contactMail=senjadisolo@gmail.com
loadingLabel=Harap Tunggu..
loginError=Login error
chatHeader=Hubungi Kami
startInfo=Selamat datang di Live Char
widgetWidth=337
widgetHeight=411
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=Mulai Live Chat
backLabel=Kembali
initMessageBody=Halo, apa ada yang bisa kami bantu ?
initMessageAuthor=CS MauDana
chatInputLabel=Tuliskan pertanyaan anda ..
timeDaysAgo=hari yang lalu
timeHoursAgo=jam yang lalu
timeMinutesAgo=menit yang lalu
timeSecondsAgo=detik yang lalu
offlineMessage=CS sedang Offline
toggleSoundLabel=Efek Suara
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emot
toggleAutoShowLabel=Auto-show
toggleFullscreenLabel=Toggle fullscreen
endChatLabel=Akhiri Live Chat
endChatConfirmQuestion=Apa anda ingin mengakhiri Live Chat ?
endChatConfirm=Ya
endChatCancel=Batalkan
contactHeader=Hubungi Kami
contactInfo=Cs Sedang Offline
contactNameLabel=Nama Anda
contactMailLabel=Email Anda
contactQuestionLabel=Pertanyaan Anda
contactSendLabel=Kirim
contactSuccessHeader=Pesan Terkirim
contactSuccessMessage=Pertanyaan anda telah terkirim, Terimakasih
contactErrorHeader=Error
contactErrorMessage=There was an error sending your question
headerHeight=45
installed=1
autoShowWidgetAfter=10
autoShowWidget=true
askForMail=true
notificationIcon=img/notification.png
